"""HyperX Pulsefire Dart protocol — re-exports from drivers.hyperx.protocol.

This module preserves backward compatibility for existing consumers.
The canonical location is now plasmangenuity.drivers.hyperx.protocol.
"""

from plasmangenuity.drivers.hyperx.protocol import *  # noqa: F401,F403
from plasmangenuity.drivers.hyperx.protocol import (  # noqa: F401 — explicit for type checkers
    PACKET_SIZE,
    CMD_HW_INFO,
    CMD_HEARTBEAT,
    CMD_LED_QUERY,
    CMD_DPI_QUERY,
    CMD_LED_SET,
    CMD_DPI_SET,
    CMD_BUTTON_SET,
    CMD_MACRO_DATA,
    CMD_SAVE,
    PollingRate,
    POLLING_RATE_HZ,
    POLLING_RATE_FROM_HZ,
    LedTarget,
    LedEffect,
    DpiMode,
    ButtonType,
    MouseButton,
    DpiFunction,
    MediaCode,
    MEDIA_CODE_NAMES,
    MacroRepeatMode,
    BUTTON_LEFT,
    BUTTON_RIGHT,
    BUTTON_MIDDLE,
    BUTTON_FORWARD,
    BUTTON_BACK,
    BUTTON_DPI,
    BUTTON_NAMES,
    HWInfo,
    BatteryStatus,
    LedSettings,
    DpiProfile,
    ButtonMapping,
    MacroEvent,
    build_heartbeat_packet,
    build_hw_info_packet,
    build_led_query_packet,
    build_dpi_query_packet,
    build_led_packet,
    build_dpi_select_packet,
    build_dpi_enable_packet,
    build_dpi_value_packet,
    build_dpi_color_packet,
    build_button_packet,
    build_macro_packets,
    build_save_packet,
    parse_hw_info,
    parse_battery,
    parse_led_settings,
    parse_dpi_settings,
)
